######################################################################
##
## Filename: testM_counter.udo
## Created on: Tue May 18 11:45:33 PM Pacific Daylight Time 2021
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
