######################################################################
##
## Filename: myReg.udo
## Created on: Wed May 19 8:45:02 AM Pacific Daylight Time 2021
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
